name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run lint
  
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run test